theme: jekyll-theme-minimal
description:  Research, Innovation and Experimentation of Internet Protocol Evolutions for Future and Emerging Applications
title: New IP and Beyond

github:
   project_tagline: Custom tagline
   owner_name: kiranmak@gmail.com
   
markdown: kramdown
